import type { UnitDefinition, UnitType } from '@core/types/unit';

export const UNIT_DEFINITIONS: Record<UnitType, UnitDefinition> = {
  INFANTRY: {
    type: 'INFANTRY',
    label: '歩兵',
    cost: 1000,
    movementType: 'FOOT',
    moveRange: 3,
    maxFuel: 99,
    maxAmmo: 9,
    visionRange: 2,
    canCapture: true,
    attackRangeMin: 1,
    attackRangeMax: 1,
  },
  RECON: {
    type: 'RECON',
    label: '偵察車',
    cost: 4000,
    movementType: 'TREAD',
    moveRange: 5,
    maxFuel: 80,
    maxAmmo: 9,
    visionRange: 4,
    canCapture: false,
    attackRangeMin: 1,
    attackRangeMax: 1,
  },
  TANK: {
    type: 'TANK',
    label: '戦車',
    cost: 7000,
    movementType: 'TREAD',
    moveRange: 4,
    maxFuel: 70,
    maxAmmo: 6,
    visionRange: 2,
    canCapture: false,
    attackRangeMin: 1,
    attackRangeMax: 1,
  },
  HEAVY_TANK: {
    type: 'HEAVY_TANK',
    label: '重戦車',
    cost: 10000,
    movementType: 'TREAD',
    moveRange: 3,
    maxFuel: 60,
    maxAmmo: 4,
    visionRange: 2,
    canCapture: false,
    attackRangeMin: 1,
    attackRangeMax: 1,
  },
  ANTI_TANK: {
    type: 'ANTI_TANK',
    label: '対戦車',
    cost: 6000,
    movementType: 'TREAD',
    moveRange: 4,
    maxFuel: 70,
    maxAmmo: 6,
    visionRange: 2,
    canCapture: false,
    attackRangeMin: 1,
    attackRangeMax: 1,
  },
  ARTILLERY: {
    type: 'ARTILLERY',
    label: '自走砲',
    cost: 6000,
    movementType: 'TREAD',
    moveRange: 3,
    maxFuel: 50,
    maxAmmo: 5,
    visionRange: 2,
    canCapture: false,
    attackRangeMin: 2,
    attackRangeMax: 3,
  },
  ANTI_AIR: {
    type: 'ANTI_AIR',
    label: '対空車',
    cost: 8000,
    movementType: 'TREAD',
    moveRange: 4,
    maxFuel: 60,
    maxAmmo: 6,
    visionRange: 2,
    canCapture: false,
    attackRangeMin: 1,
    attackRangeMax: 1,
  },
  FLAK_TANK: {
    type: 'FLAK_TANK',
    label: '高射砲車',
    cost: 11000,
    movementType: 'TREAD',
    moveRange: 3,
    maxFuel: 55,
    maxAmmo: 6,
    visionRange: 4,
    canCapture: false,
    attackRangeMin: 2,
    attackRangeMax: 3,
  },
  MISSILE_AA: {
    type: 'MISSILE_AA',
    label: '地対空ミサイル車',
    cost: 9000,
    movementType: 'WHEEL',
    moveRange: 3,
    maxFuel: 50,
    maxAmmo: 5,
    visionRange: 5,
    canCapture: false,
    attackRangeMin: 2,
    attackRangeMax: 4,
  },
  SUPPLY_TRUCK: {
    type: 'SUPPLY_TRUCK',
    label: '補給車',
    cost: 3000,
    movementType: 'WHEEL',
    moveRange: 5,
    maxFuel: 70,
    maxAmmo: 0,
    visionRange: 2,
    canCapture: false,
    attackRangeMin: 1,
    attackRangeMax: 1,
    resupplyTarget: 'GROUND',
  },
  TRANSPORT_TRUCK: {
    type: 'TRANSPORT_TRUCK',
    label: '輸送車',
    cost: 5000,
    movementType: 'WHEEL',
    moveRange: 7,
    maxFuel: 80,
    maxAmmo: 0,
    visionRange: 1,
    canCapture: false,
    attackRangeMin: 1,
    attackRangeMax: 1,
    transportMode: 'GROUND',
    cargoCapacity: 2,
    cargoUnitTypes: ['INFANTRY', 'RECON', 'ANTI_TANK', 'ARTILLERY', 'ANTI_AIR', 'SUPPLY_TRUCK', 'FLAK_TANK', 'MISSILE_AA', 'COUNTER_DRONE_AA', 'AIR_DEFENSE_INFANTRY'],
    canUnloadAfterMove: true,
  },
  AIR_DEFENSE_INFANTRY: {
    type: 'AIR_DEFENSE_INFANTRY',
    label: '防空歩兵',
    cost: 4000,
    movementType: 'FOOT',
    moveRange: 2,
    maxFuel: 99,
    maxAmmo: 6,
    visionRange: 3,
    canCapture: true,
    attackRangeMin: 1,
    attackRangeMax: 1,
  },
  COUNTER_DRONE_AA: {
    type: 'COUNTER_DRONE_AA',
    label: '対ドローン防空車',
    cost: 7000,
    movementType: 'TREAD',
    moveRange: 4,
    maxFuel: 60,
    maxAmmo: 6,
    visionRange: 4,
    canCapture: false,
    attackRangeMin: 1,
    attackRangeMax: 2,
    interceptRange: 2,
  },
  SUICIDE_DRONE: {
    type: 'SUICIDE_DRONE',
    label: '自爆ドローン',
    cost: 1500,
    movementType: 'AIR',
    unitCategory: 'DRONE',
    moveRange: 6,
    maxFuel: 50,
    maxAmmo: 1,
    visionRange: 3,
    canCapture: false,
    attackRangeMin: 1,
    attackRangeMax: 1,
    turnEndFuelCost: 1,
  },
  FIGHTER: {
    type: 'FIGHTER',
    label: '戦闘機',
    cost: 14000,
    movementType: 'AIR',
    moveRange: 8,
    maxFuel: 80,
    maxAmmo: 6,
    visionRange: 4,
    canCapture: false,
    attackRangeMin: 1,
    attackRangeMax: 1,
    turnEndFuelCost: 1,
  },
  BOMBER: {
    type: 'BOMBER',
    label: '爆撃機',
    cost: 16000,
    movementType: 'AIR',
    moveRange: 7,
    maxFuel: 80,
    maxAmmo: 6,
    visionRange: 3,
    canCapture: false,
    attackRangeMin: 1,
    attackRangeMax: 1,
    canBombardProperties: true,
    turnEndFuelCost: 1,
  },
  ATTACKER: {
    type: 'ATTACKER',
    label: '攻撃機',
    cost: 11000,
    movementType: 'AIR',
    moveRange: 5,
    maxFuel: 60,
    maxAmmo: 4,
    visionRange: 2,
    canCapture: false,
    attackRangeMin: 1,
    attackRangeMax: 1,
    turnEndFuelCost: 1,
  },
  STEALTH_BOMBER: {
    type: 'STEALTH_BOMBER',
    label: 'ステルス爆撃機',
    cost: 20000,
    movementType: 'AIR',
    moveRange: 7,
    maxFuel: 60,
    maxAmmo: 5,
    visionRange: 5,
    canCapture: false,
    attackRangeMin: 1,
    attackRangeMax: 1,
    canBombardProperties: true,
    isStealth: true,
    turnEndFuelCost: 2,
  },
  AIR_TANKER: {
    type: 'AIR_TANKER',
    label: '空中補給機',
    cost: 10000,
    movementType: 'AIR',
    moveRange: 6,
    maxFuel: 80,
    maxAmmo: 0,
    visionRange: 3,
    canCapture: false,
    attackRangeMin: 1,
    attackRangeMax: 1,
    turnEndFuelCost: 1,
    resupplyTarget: 'AIR',
  },
  TRANSPORT_HELI: {
    type: 'TRANSPORT_HELI',
    label: '輸送ヘリ',
    cost: 6000,
    movementType: 'AIR',
    moveRange: 6,
    maxFuel: 70,
    maxAmmo: 0,
    visionRange: 2,
    canCapture: false,
    attackRangeMin: 1,
    attackRangeMax: 1,
    turnEndFuelCost: 1,
    transportMode: 'AIR',
    cargoCapacity: 1,
    cargoUnitTypes: ['INFANTRY', 'AIR_DEFENSE_INFANTRY'],
    canUnloadAfterMove: true,
  },
  CARRIER: {
    type: 'CARRIER',
    label: '空母',
    cost: 30000,
    movementType: 'NAVAL',
    moveRange: 3,
    maxFuel: 99,
    maxAmmo: 4,
    visionRange: 4,
    canCapture: false,
    attackRangeMin: 1,
    attackRangeMax: 1,
    transportMode: 'NAVAL',
    cargoCapacity: 2,
    cargoUnitTypes: ['FIGHTER', 'BOMBER', 'ATTACKER', 'STEALTH_BOMBER', 'AIR_TANKER', 'TRANSPORT_HELI'],
    canUnloadAfterMove: true,
  },
  SUBMARINE: {
    type: 'SUBMARINE',
    label: '潜水艦',
    cost: 18000,
    movementType: 'NAVAL',
    moveRange: 3,
    maxFuel: 65,
    maxAmmo: 4,
    visionRange: 4,
    canCapture: false,
    attackRangeMin: 1,
    attackRangeMax: 1,
    isStealth: true,
  },
  BATTLESHIP: {
    type: 'BATTLESHIP',
    label: '戦艦',
    cost: 30000,
    movementType: 'NAVAL',
    moveRange: 3,
    maxFuel: 99,
    maxAmmo: 6,
    visionRange: 3,
    canCapture: false,
    attackRangeMin: 1,
    attackRangeMax: 5,
  },
  SUPPLY_SHIP: {
    type: 'SUPPLY_SHIP',
    label: '補給艦',
    cost: 12000,
    movementType: 'NAVAL',
    moveRange: 3,
    maxFuel: 99,
    maxAmmo: 0,
    visionRange: 1,
    canCapture: false,
    attackRangeMin: 1,
    attackRangeMax: 1,
    resupplyTarget: 'NAVAL',
  },
  DESTROYER: {
    type: 'DESTROYER',
    label: '駆逐艦',
    cost: 20000,
    movementType: 'NAVAL',
    moveRange: 4,
    maxFuel: 99,
    maxAmmo: 6,
    visionRange: 3,
    canCapture: false,
    attackRangeMin: 1,
    attackRangeMax: 2,
  },
  LANDER: {
    type: 'LANDER',
    label: '揚陸艦',
    cost: 12000,
    movementType: 'NAVAL',
    moveRange: 3,
    maxFuel: 99,
    maxAmmo: 0,
    visionRange: 1,
    canCapture: false,
    attackRangeMin: 1,
    attackRangeMax: 1,
    transportMode: 'NAVAL',
    cargoCapacity: 2,
    cargoUnitTypes: [
      'INFANTRY',
      'RECON',
      'TANK',
      'HEAVY_TANK',
      'ANTI_TANK',
      'ARTILLERY',
      'ANTI_AIR',
      'FLAK_TANK',
      'MISSILE_AA',
      'SUPPLY_TRUCK',
      'TRANSPORT_TRUCK',
      'AIR_DEFENSE_INFANTRY',
      'COUNTER_DRONE_AA',
      'SUICIDE_DRONE',
    ],
    canUnloadAfterMove: true,
  },
};

export const BASE_DAMAGE_TABLE: Record<UnitType, Record<UnitType, number>> = {
  INFANTRY: {
    INFANTRY: 55, RECON: 20, TANK: 10, HEAVY_TANK: 5, ANTI_TANK: 8, ARTILLERY: 20, ANTI_AIR: 12, FLAK_TANK: 20, MISSILE_AA: 25,
    SUPPLY_TRUCK: 25, TRANSPORT_TRUCK: 20, AIR_DEFENSE_INFANTRY: 45, COUNTER_DRONE_AA: 12, SUICIDE_DRONE: 20,
    FIGHTER: 0, BOMBER: 0, ATTACKER: 0, STEALTH_BOMBER: 0, AIR_TANKER: 0, TRANSPORT_HELI: 0, CARRIER: 0, SUBMARINE: 0, BATTLESHIP: 0, SUPPLY_SHIP: 0, DESTROYER: 0, LANDER: 0,
  },
  RECON: {
    INFANTRY: 50, RECON: 35, TANK: 15, HEAVY_TANK: 10, ANTI_TANK: 10, ARTILLERY: 45, ANTI_AIR: 12, FLAK_TANK: 50, MISSILE_AA: 55,
    SUPPLY_TRUCK: 45, TRANSPORT_TRUCK: 35, AIR_DEFENSE_INFANTRY: 45, COUNTER_DRONE_AA: 18, SUICIDE_DRONE: 20,
    FIGHTER: 0, BOMBER: 0, ATTACKER: 0, STEALTH_BOMBER: 0, AIR_TANKER: 0, TRANSPORT_HELI: 0, CARRIER: 0, SUBMARINE: 0, BATTLESHIP: 0, SUPPLY_SHIP: 0, DESTROYER: 0, LANDER: 0,
  },
  TANK: {
    INFANTRY: 75, RECON: 80, TANK: 55, HEAVY_TANK: 35, ANTI_TANK: 45, ARTILLERY: 70, ANTI_AIR: 65, FLAK_TANK: 75, MISSILE_AA: 80,
    SUPPLY_TRUCK: 100, TRANSPORT_TRUCK: 80, AIR_DEFENSE_INFANTRY: 85, COUNTER_DRONE_AA: 70, SUICIDE_DRONE: 25,
    FIGHTER: 0, BOMBER: 0, ATTACKER: 0, STEALTH_BOMBER: 0, AIR_TANKER: 0, TRANSPORT_HELI: 0, CARRIER: 0, SUBMARINE: 0, BATTLESHIP: 0, SUPPLY_SHIP: 0, DESTROYER: 0, LANDER: 0,
  },
  HEAVY_TANK: {
    INFANTRY: 95, RECON: 95, TANK: 75, HEAVY_TANK: 55, ANTI_TANK: 55, ARTILLERY: 85, ANTI_AIR: 75, FLAK_TANK: 85, MISSILE_AA: 90,
    SUPPLY_TRUCK: 120, TRANSPORT_TRUCK: 95, AIR_DEFENSE_INFANTRY: 95, COUNTER_DRONE_AA: 95, SUICIDE_DRONE: 30,
    FIGHTER: 0, BOMBER: 0, ATTACKER: 0, STEALTH_BOMBER: 0, AIR_TANKER: 0, TRANSPORT_HELI: 0, CARRIER: 0, SUBMARINE: 0, BATTLESHIP: 0, SUPPLY_SHIP: 0, DESTROYER: 0, LANDER: 0,
  },
  ANTI_TANK: {
    INFANTRY: 45, RECON: 50, TANK: 80, HEAVY_TANK: 65, ANTI_TANK: 50, ARTILLERY: 40, ANTI_AIR: 40, FLAK_TANK: 40, MISSILE_AA: 60,
    SUPPLY_TRUCK: 60, TRANSPORT_TRUCK: 50, AIR_DEFENSE_INFANTRY: 45, COUNTER_DRONE_AA: 50, SUICIDE_DRONE: 25,
    FIGHTER: 0, BOMBER: 0, ATTACKER: 0, STEALTH_BOMBER: 0, AIR_TANKER: 0, TRANSPORT_HELI: 0, CARRIER: 0, SUBMARINE: 0, BATTLESHIP: 0, SUPPLY_SHIP: 0, DESTROYER: 0, LANDER: 0,
  },
  ARTILLERY: {
    INFANTRY: 80, RECON: 75, TANK: 45, HEAVY_TANK: 35, ANTI_TANK: 50, ARTILLERY: 60, ANTI_AIR: 60, FLAK_TANK: 60, MISSILE_AA: 75,
    SUPPLY_TRUCK: 95, TRANSPORT_TRUCK: 75, AIR_DEFENSE_INFANTRY: 70, COUNTER_DRONE_AA: 55, SUICIDE_DRONE: 25,
    FIGHTER: 0, BOMBER: 0, ATTACKER: 0, STEALTH_BOMBER: 0, AIR_TANKER: 0, TRANSPORT_HELI: 0, CARRIER: 0, SUBMARINE: 0, BATTLESHIP: 0, SUPPLY_SHIP: 0, DESTROYER: 0, LANDER: 0,
  },
  ANTI_AIR: {
    INFANTRY: 60, RECON: 50, TANK: 25, HEAVY_TANK: 15, ANTI_TANK: 35, ARTILLERY: 40, ANTI_AIR: 55, FLAK_TANK: 50, MISSILE_AA: 60,
    SUPPLY_TRUCK: 120, TRANSPORT_TRUCK: 50, AIR_DEFENSE_INFANTRY: 65, COUNTER_DRONE_AA: 55, SUICIDE_DRONE: 90,
    FIGHTER: 65, BOMBER: 65, ATTACKER: 80, STEALTH_BOMBER: 60, AIR_TANKER: 90, TRANSPORT_HELI: 100, CARRIER: 0, SUBMARINE: 0, BATTLESHIP: 0, SUPPLY_SHIP: 0, DESTROYER: 0, LANDER: 0,
  },
  FLAK_TANK: {
    INFANTRY: 55, RECON: 45, TANK: 15, HEAVY_TANK: 10, ANTI_TANK: 20, ARTILLERY: 35, ANTI_AIR: 30, FLAK_TANK: 30, MISSILE_AA: 35,
    SUPPLY_TRUCK: 55, TRANSPORT_TRUCK: 45, AIR_DEFENSE_INFANTRY: 45, COUNTER_DRONE_AA: 35, SUICIDE_DRONE: 110,
    FIGHTER: 80, BOMBER: 90, ATTACKER: 100, STEALTH_BOMBER: 85, AIR_TANKER: 105, TRANSPORT_HELI: 110, CARRIER: 0, SUBMARINE: 0, BATTLESHIP: 0, SUPPLY_SHIP: 0, DESTROYER: 0, LANDER: 0,
  },
  MISSILE_AA: {
    INFANTRY: 0, RECON: 0, TANK: 0, HEAVY_TANK: 0, ANTI_TANK: 0, ARTILLERY: 0, ANTI_AIR: 0, FLAK_TANK: 0, MISSILE_AA: 0,
    SUPPLY_TRUCK: 0, TRANSPORT_TRUCK: 0, AIR_DEFENSE_INFANTRY: 0, COUNTER_DRONE_AA: 0, SUICIDE_DRONE: 120,
    FIGHTER: 95, BOMBER: 105, ATTACKER: 115, STEALTH_BOMBER: 100, AIR_TANKER: 120, TRANSPORT_HELI: 125, CARRIER: 0, SUBMARINE: 0, BATTLESHIP: 0, SUPPLY_SHIP: 0, DESTROYER: 0, LANDER: 0,
  },
  SUPPLY_TRUCK: {
    INFANTRY: 0, RECON: 0, TANK: 0, HEAVY_TANK: 0, ANTI_TANK: 0, ARTILLERY: 0, ANTI_AIR: 0, FLAK_TANK: 0, MISSILE_AA: 0,
    SUPPLY_TRUCK: 0, TRANSPORT_TRUCK: 0, AIR_DEFENSE_INFANTRY: 0, COUNTER_DRONE_AA: 0, SUICIDE_DRONE: 0,
    FIGHTER: 0, BOMBER: 0, ATTACKER: 0, STEALTH_BOMBER: 0, AIR_TANKER: 0, TRANSPORT_HELI: 0, CARRIER: 0, SUBMARINE: 0, BATTLESHIP: 0, SUPPLY_SHIP: 0, DESTROYER: 0, LANDER: 0,
  },
  TRANSPORT_TRUCK: {
    INFANTRY: 0, RECON: 0, TANK: 0, HEAVY_TANK: 0, ANTI_TANK: 0, ARTILLERY: 0, ANTI_AIR: 0, FLAK_TANK: 0, MISSILE_AA: 0,
    SUPPLY_TRUCK: 0, TRANSPORT_TRUCK: 0, AIR_DEFENSE_INFANTRY: 0, COUNTER_DRONE_AA: 0, SUICIDE_DRONE: 0,
    FIGHTER: 0, BOMBER: 0, ATTACKER: 0, STEALTH_BOMBER: 0, AIR_TANKER: 0, TRANSPORT_HELI: 0, CARRIER: 0, SUBMARINE: 0, BATTLESHIP: 0, SUPPLY_SHIP: 0, DESTROYER: 0, LANDER: 0,
  },
  AIR_DEFENSE_INFANTRY: {
    INFANTRY: 45, RECON: 15, TANK: 10, HEAVY_TANK: 5, ANTI_TANK: 8, ARTILLERY: 15, ANTI_AIR: 12, FLAK_TANK: 15, MISSILE_AA: 20,
    SUPPLY_TRUCK: 25, TRANSPORT_TRUCK: 20, AIR_DEFENSE_INFANTRY: 50, COUNTER_DRONE_AA: 20, SUICIDE_DRONE: 80,
    FIGHTER: 25, BOMBER: 25, ATTACKER: 28, STEALTH_BOMBER: 22, AIR_TANKER: 28, TRANSPORT_HELI: 30, CARRIER: 0, SUBMARINE: 0, BATTLESHIP: 0, SUPPLY_SHIP: 0, DESTROYER: 0, LANDER: 0,
  },
  COUNTER_DRONE_AA: {
    INFANTRY: 55, RECON: 22, TANK: 10, HEAVY_TANK: 5, ANTI_TANK: 8, ARTILLERY: 20, ANTI_AIR: 12, FLAK_TANK: 18, MISSILE_AA: 20,
    SUPPLY_TRUCK: 25, TRANSPORT_TRUCK: 20, AIR_DEFENSE_INFANTRY: 40, COUNTER_DRONE_AA: 30, SUICIDE_DRONE: 120,
    FIGHTER: 25, BOMBER: 25, ATTACKER: 25, STEALTH_BOMBER: 22, AIR_TANKER: 30, TRANSPORT_HELI: 30, CARRIER: 0, SUBMARINE: 0, BATTLESHIP: 0, SUPPLY_SHIP: 0, DESTROYER: 0, LANDER: 0,
  },
  SUICIDE_DRONE: {
    INFANTRY: 50, RECON: 50, TANK: 35, HEAVY_TANK: 25, ANTI_TANK: 35, ARTILLERY: 35, ANTI_AIR: 35, FLAK_TANK: 35, MISSILE_AA: 35,
    SUPPLY_TRUCK: 50, TRANSPORT_TRUCK: 50, AIR_DEFENSE_INFANTRY: 45, COUNTER_DRONE_AA: 25, SUICIDE_DRONE: 50,
    FIGHTER: 0, BOMBER: 20, ATTACKER: 50, STEALTH_BOMBER: 20, AIR_TANKER: 50, TRANSPORT_HELI: 50, CARRIER: 35, SUBMARINE: 35, BATTLESHIP: 35, SUPPLY_SHIP: 50, DESTROYER: 35, LANDER: 35,
  },
  FIGHTER: {
    INFANTRY: 0, RECON: 0, TANK: 0, HEAVY_TANK: 0, ANTI_TANK: 0, ARTILLERY: 0, ANTI_AIR: 0, FLAK_TANK: 0, MISSILE_AA: 0,
    SUPPLY_TRUCK: 0, TRANSPORT_TRUCK: 0, AIR_DEFENSE_INFANTRY: 0, COUNTER_DRONE_AA: 0, SUICIDE_DRONE: 120,
    FIGHTER: 65, BOMBER: 85, ATTACKER: 105, STEALTH_BOMBER: 75, AIR_TANKER: 115, TRANSPORT_HELI: 120, CARRIER: 25, SUBMARINE: 0, BATTLESHIP: 20, SUPPLY_SHIP: 35, DESTROYER: 0, LANDER: 0,
  },
  BOMBER: {
    INFANTRY: 110, RECON: 105, TANK: 80, HEAVY_TANK: 65, ANTI_TANK: 80, ARTILLERY: 80, ANTI_AIR: 30, FLAK_TANK: 35, MISSILE_AA: 40,
    SUPPLY_TRUCK: 120, TRANSPORT_TRUCK: 105, AIR_DEFENSE_INFANTRY: 100, COUNTER_DRONE_AA: 70, SUICIDE_DRONE: 0,
    FIGHTER: 0, BOMBER: 0, ATTACKER: 0, STEALTH_BOMBER: 0, AIR_TANKER: 0, TRANSPORT_HELI: 0, CARRIER: 20, SUBMARINE: 0, BATTLESHIP: 35, SUPPLY_SHIP: 60, DESTROYER: 0, LANDER: 0,
  },
  ATTACKER: {
    INFANTRY: 95, RECON: 95, TANK: 60, HEAVY_TANK: 45, ANTI_TANK: 60, ARTILLERY: 60, ANTI_AIR: 20, FLAK_TANK: 25, MISSILE_AA: 30,
    SUPPLY_TRUCK: 105, TRANSPORT_TRUCK: 95, AIR_DEFENSE_INFANTRY: 85, COUNTER_DRONE_AA: 55, SUICIDE_DRONE: 0,
    FIGHTER: 0, BOMBER: 0, ATTACKER: 0, STEALTH_BOMBER: 0, AIR_TANKER: 0, TRANSPORT_HELI: 0, CARRIER: 20, SUBMARINE: 0, BATTLESHIP: 30, SUPPLY_SHIP: 55, DESTROYER: 0, LANDER: 0,
  },
  STEALTH_BOMBER: {
    INFANTRY: 110, RECON: 90, TANK: 75, HEAVY_TANK: 60, ANTI_TANK: 70, ARTILLERY: 80, ANTI_AIR: 40, FLAK_TANK: 0, MISSILE_AA: 0,
    SUPPLY_TRUCK: 100, TRANSPORT_TRUCK: 90, AIR_DEFENSE_INFANTRY: 90, COUNTER_DRONE_AA: 60, SUICIDE_DRONE: 35,
    FIGHTER: 30, BOMBER: 70, ATTACKER: 80, STEALTH_BOMBER: 55, AIR_TANKER: 90, TRANSPORT_HELI: 95, CARRIER: 20, SUBMARINE: 0, BATTLESHIP: 35, SUPPLY_SHIP: 60, DESTROYER: 0, LANDER: 0,
  },
  AIR_TANKER: {
    INFANTRY: 0, RECON: 0, TANK: 0, HEAVY_TANK: 0, ANTI_TANK: 0, ARTILLERY: 0, ANTI_AIR: 0, FLAK_TANK: 0, MISSILE_AA: 0,
    SUPPLY_TRUCK: 0, TRANSPORT_TRUCK: 0, AIR_DEFENSE_INFANTRY: 0, COUNTER_DRONE_AA: 0, SUICIDE_DRONE: 0,
    FIGHTER: 0, BOMBER: 0, ATTACKER: 0, STEALTH_BOMBER: 0, AIR_TANKER: 0, TRANSPORT_HELI: 0, CARRIER: 0, SUBMARINE: 0, BATTLESHIP: 0, SUPPLY_SHIP: 0, DESTROYER: 0, LANDER: 0,
  },
  TRANSPORT_HELI: {
    INFANTRY: 0, RECON: 0, TANK: 0, HEAVY_TANK: 0, ANTI_TANK: 0, ARTILLERY: 0, ANTI_AIR: 0, FLAK_TANK: 0, MISSILE_AA: 0,
    SUPPLY_TRUCK: 0, TRANSPORT_TRUCK: 0, AIR_DEFENSE_INFANTRY: 0, COUNTER_DRONE_AA: 0, SUICIDE_DRONE: 0,
    FIGHTER: 0, BOMBER: 0, ATTACKER: 0, STEALTH_BOMBER: 0, AIR_TANKER: 0, TRANSPORT_HELI: 0, CARRIER: 0, SUBMARINE: 0, BATTLESHIP: 0, SUPPLY_SHIP: 0, DESTROYER: 0, LANDER: 0,
  },
  DESTROYER: {
    INFANTRY: 50, RECON: 0, TANK: 45, HEAVY_TANK: 35, ANTI_TANK: 0, ARTILLERY: 60, ANTI_AIR: 0, FLAK_TANK: 0, MISSILE_AA: 0,
    SUPPLY_TRUCK: 65, TRANSPORT_TRUCK: 0, AIR_DEFENSE_INFANTRY: 40, COUNTER_DRONE_AA: 20, SUICIDE_DRONE: 40,
    FIGHTER: 0, BOMBER: 0, ATTACKER: 0, STEALTH_BOMBER: 0, AIR_TANKER: 0, TRANSPORT_HELI: 0, CARRIER: 15, SUBMARINE: 35, BATTLESHIP: 15, SUPPLY_SHIP: 95, DESTROYER: 70, LANDER: 90,
  },
  LANDER: {
    INFANTRY: 0, RECON: 0, TANK: 0, HEAVY_TANK: 0, ANTI_TANK: 0, ARTILLERY: 0, ANTI_AIR: 0, FLAK_TANK: 0, MISSILE_AA: 0,
    SUPPLY_TRUCK: 0, TRANSPORT_TRUCK: 0, AIR_DEFENSE_INFANTRY: 0, COUNTER_DRONE_AA: 0, SUICIDE_DRONE: 0,
    FIGHTER: 0, BOMBER: 0, ATTACKER: 0, STEALTH_BOMBER: 0, AIR_TANKER: 0, TRANSPORT_HELI: 0, CARRIER: 0, SUBMARINE: 0, BATTLESHIP: 0, SUPPLY_SHIP: 0, DESTROYER: 0, LANDER: 0,
  },
  CARRIER: {
    INFANTRY: 0, RECON: 0, TANK: 0, HEAVY_TANK: 0, ANTI_TANK: 0, ARTILLERY: 0, ANTI_AIR: 0, FLAK_TANK: 0, MISSILE_AA: 0,
    SUPPLY_TRUCK: 0, TRANSPORT_TRUCK: 0, AIR_DEFENSE_INFANTRY: 0, COUNTER_DRONE_AA: 0, SUICIDE_DRONE: 0,
    FIGHTER: 25, BOMBER: 25, ATTACKER: 30, STEALTH_BOMBER: 20, AIR_TANKER: 25, TRANSPORT_HELI: 30, CARRIER: 15, SUBMARINE: 5, BATTLESHIP: 10, SUPPLY_SHIP: 20, DESTROYER: 15, LANDER: 20,
  },
  SUBMARINE: {
    INFANTRY: 0, RECON: 0, TANK: 0, HEAVY_TANK: 0, ANTI_TANK: 0, ARTILLERY: 0, ANTI_AIR: 0, FLAK_TANK: 0, MISSILE_AA: 0,
    SUPPLY_TRUCK: 0, TRANSPORT_TRUCK: 0, AIR_DEFENSE_INFANTRY: 0, COUNTER_DRONE_AA: 0, SUICIDE_DRONE: 0,
    FIGHTER: 0, BOMBER: 0, ATTACKER: 0, STEALTH_BOMBER: 0, AIR_TANKER: 0, TRANSPORT_HELI: 0, CARRIER: 60, SUBMARINE: 55, BATTLESHIP: 75, SUPPLY_SHIP: 85, DESTROYER: 25, LANDER: 90,
  },
  BATTLESHIP: {
    INFANTRY: 100, RECON: 85, TANK: 80, HEAVY_TANK: 65, ANTI_TANK: 80, ARTILLERY: 85, ANTI_AIR: 75, FLAK_TANK: 80, MISSILE_AA: 85,
    SUPPLY_TRUCK: 95, TRANSPORT_TRUCK: 85, AIR_DEFENSE_INFANTRY: 100, COUNTER_DRONE_AA: 75, SUICIDE_DRONE: 0,
    FIGHTER: 0, BOMBER: 0, ATTACKER: 0, STEALTH_BOMBER: 0, AIR_TANKER: 0, TRANSPORT_HELI: 0, CARRIER: 35, SUBMARINE: 0, BATTLESHIP: 35, SUPPLY_SHIP: 70, DESTROYER: 35, LANDER: 85,
  },
  SUPPLY_SHIP: {
    INFANTRY: 0, RECON: 0, TANK: 0, HEAVY_TANK: 0, ANTI_TANK: 0, ARTILLERY: 0, ANTI_AIR: 0, FLAK_TANK: 0, MISSILE_AA: 0,
    SUPPLY_TRUCK: 0, TRANSPORT_TRUCK: 0, AIR_DEFENSE_INFANTRY: 0, COUNTER_DRONE_AA: 0, SUICIDE_DRONE: 0,
    FIGHTER: 0, BOMBER: 0, ATTACKER: 0, STEALTH_BOMBER: 0, AIR_TANKER: 0, TRANSPORT_HELI: 0, CARRIER: 0, SUBMARINE: 0, BATTLESHIP: 0, SUPPLY_SHIP: 0, DESTROYER: 0, LANDER: 0,
  },
};

export const getBaseDamage = (attackerType: UnitType, defenderType: UnitType): number =>
  BASE_DAMAGE_TABLE[attackerType][defenderType];
