import type { UnitDefinition, UnitType } from '@core/types/unit';

export const UNIT_DEFINITIONS: Record<UnitType, UnitDefinition> = {
  INFANTRY: {
    type: 'INFANTRY',
    label: '歩兵',
    cost: 1000,
    movementType: 'FOOT',
    moveRange: 3,
    maxFuel: 99,
    maxAmmo: 9,
    visionRange: 2,
    canCapture: true,
    attackRangeMin: 1,
    attackRangeMax: 1,
  },
  RECON: {
    type: 'RECON',
    label: '偵察車',
    cost: 4000,
    movementType: 'WHEEL',
    moveRange: 6,
    maxFuel: 80,
    maxAmmo: 9,
    visionRange: 4,
    canCapture: false,
    attackRangeMin: 1,
    attackRangeMax: 1,
  },
  TANK: {
    type: 'TANK',
    label: '戦車',
    cost: 7000,
    movementType: 'TREAD',
    moveRange: 5,
    maxFuel: 70,
    maxAmmo: 6,
    visionRange: 3,
    canCapture: false,
    attackRangeMin: 1,
    attackRangeMax: 1,
  },
  HEAVY_TANK: {
    type: 'HEAVY_TANK',
    label: '重戦車',
    cost: 10000,
    movementType: 'TREAD',
    moveRange: 4,
    maxFuel: 60,
    maxAmmo: 4,
    visionRange: 3,
    canCapture: false,
    attackRangeMin: 1,
    attackRangeMax: 1,
  },
  ANTI_TANK: {
    type: 'ANTI_TANK',
    label: '対戦車',
    cost: 6000,
    movementType: 'TREAD',
    moveRange: 4,
    maxFuel: 70,
    maxAmmo: 6,
    visionRange: 3,
    canCapture: false,
    attackRangeMin: 1,
    attackRangeMax: 1,
  },
  ARTILLERY: {
    type: 'ARTILLERY',
    label: '自走砲',
    cost: 6000,
    movementType: 'TREAD',
    moveRange: 4,
    maxFuel: 50,
    maxAmmo: 6,
    visionRange: 3,
    canCapture: false,
    attackRangeMin: 2,
    attackRangeMax: 3,
  },
  ANTI_AIR: {
    type: 'ANTI_AIR',
    label: '対空車',
    cost: 8000,
    movementType: 'TREAD',
    moveRange: 5,
    maxFuel: 60,
    maxAmmo: 6,
    visionRange: 3,
    canCapture: false,
    attackRangeMin: 1,
    attackRangeMax: 1,
  },
  FLAK_TANK: {
    type: 'FLAK_TANK',
    label: '高射砲車',
    cost: 11000,
    movementType: 'TREAD',
    moveRange: 3,
    maxFuel: 55,
    maxAmmo: 6,
    visionRange: 5,
    canCapture: false,
    attackRangeMin: 2,
    attackRangeMax: 4,
  },
  MISSILE_AA: {
    type: 'MISSILE_AA',
    label: '地対空ミサイル車',
    cost: 9000,
    movementType: 'WHEEL',
    moveRange: 3,
    maxFuel: 50,
    maxAmmo: 5,
    visionRange: 6,
    canCapture: false,
    attackRangeMin: 2,
    attackRangeMax: 4,
  },
  SUPPLY_TRUCK: {
    type: 'SUPPLY_TRUCK',
    label: '補給車',
    cost: 3000,
    movementType: 'WHEEL',
    moveRange: 5,
    maxFuel: 70,
    maxAmmo: 0,
    visionRange: 2,
    canCapture: false,
    attackRangeMin: 1,
    attackRangeMax: 1,
    resupplyTarget: 'GROUND',
  },
  TRANSPORT_TRUCK: {
    type: 'TRANSPORT_TRUCK',
    label: '輸送車',
    cost: 5000,
    movementType: 'WHEEL',
    moveRange: 6,
    maxFuel: 80,
    maxAmmo: 0,
    visionRange: 3,
    canCapture: false,
    attackRangeMin: 1,
    attackRangeMax: 1,
    transportMode: 'GROUND',
    cargoCapacity: 2,
    cargoUnitTypes: ['INFANTRY', 'RECON', 'ANTI_TANK', 'ARTILLERY', 'ANTI_AIR', 'SUPPLY_TRUCK', 'FLAK_TANK', 'MISSILE_AA'],
    canUnloadAfterMove: true,
  },
  FIGHTER: {
    type: 'FIGHTER',
    label: '戦闘機',
    cost: 14000,
    movementType: 'AIR',
    moveRange: 8,
    maxFuel: 80,
    maxAmmo: 6,
    visionRange: 5,
    canCapture: false,
    attackRangeMin: 1,
    attackRangeMax: 1,
    turnEndFuelCost: 1,
  },
  BOMBER: {
    type: 'BOMBER',
    label: '爆撃機',
    cost: 16000,
    movementType: 'AIR',
    moveRange: 7,
    maxFuel: 80,
    maxAmmo: 6,
    visionRange: 3,
    canCapture: false,
    attackRangeMin: 1,
    attackRangeMax: 1,
    canBombardProperties: true,
    turnEndFuelCost: 1,
  },
  ATTACKER: {
    type: 'ATTACKER',
    label: '攻撃機',
    cost: 11000,
    movementType: 'AIR',
    moveRange: 5,
    maxFuel: 60,
    maxAmmo: 4,
    visionRange: 2,
    canCapture: false,
    attackRangeMin: 1,
    attackRangeMax: 1,
    turnEndFuelCost: 1,
  },
  STEALTH_BOMBER: {
    type: 'STEALTH_BOMBER',
    label: 'ステルス爆撃機',
    cost: 20000,
    movementType: 'AIR',
    moveRange: 8,
    maxFuel: 60,
    maxAmmo: 5,
    visionRange: 4,
    canCapture: false,
    attackRangeMin: 1,
    attackRangeMax: 1,
    canBombardProperties: true,
    isStealth: true,
    turnEndFuelCost: 2,
  },
  AIR_TANKER: {
    type: 'AIR_TANKER',
    label: '空中補給機',
    cost: 10000,
    movementType: 'AIR',
    moveRange: 6,
    maxFuel: 80,
    maxAmmo: 0,
    visionRange: 3,
    canCapture: false,
    attackRangeMin: 1,
    attackRangeMax: 1,
    turnEndFuelCost: 1,
    resupplyTarget: 'AIR',
  },
  TRANSPORT_HELI: {
    type: 'TRANSPORT_HELI',
    label: '輸送ヘリ',
    cost: 6000,
    movementType: 'AIR',
    moveRange: 6,
    maxFuel: 70,
    maxAmmo: 0,
    visionRange: 2,
    canCapture: false,
    attackRangeMin: 1,
    attackRangeMax: 1,
    turnEndFuelCost: 1,
    transportMode: 'AIR',
    cargoCapacity: 1,
    cargoUnitTypes: ['INFANTRY'],
    canUnloadAfterMove: true,
  },
  DESTROYER: {
    type: 'DESTROYER',
    label: '駆逐艦',
    cost: 20000,
    movementType: 'NAVAL',
    moveRange: 6,
    maxFuel: 99,
    maxAmmo: 6,
    visionRange: 4,
    canCapture: false,
    attackRangeMin: 1,
    attackRangeMax: 2,
  },
  LANDER: {
    type: 'LANDER',
    label: '揚陸艦',
    cost: 12000,
    movementType: 'NAVAL',
    moveRange: 6,
    maxFuel: 99,
    maxAmmo: 0,
    visionRange: 3,
    canCapture: false,
    attackRangeMin: 1,
    attackRangeMax: 1,
  },
};

export const BASE_DAMAGE_TABLE: Record<UnitType, Record<UnitType, number>> = {
  INFANTRY: {
    INFANTRY: 55, RECON: 20, TANK: 10, HEAVY_TANK: 5, ANTI_TANK: 8, ARTILLERY: 20, ANTI_AIR: 12, FLAK_TANK: 20, MISSILE_AA: 25,
    SUPPLY_TRUCK: 25, TRANSPORT_TRUCK: 20, FIGHTER: 0, BOMBER: 0, ATTACKER: 0, STEALTH_BOMBER: 0, AIR_TANKER: 0, TRANSPORT_HELI: 0, DESTROYER: 0, LANDER: 0,
  },
  RECON: {
    INFANTRY: 50, RECON: 35, TANK: 15, HEAVY_TANK: 10, ANTI_TANK: 10, ARTILLERY: 45, ANTI_AIR: 12, FLAK_TANK: 50, MISSILE_AA: 55,
    SUPPLY_TRUCK: 45, TRANSPORT_TRUCK: 35, FIGHTER: 0, BOMBER: 0, ATTACKER: 0, STEALTH_BOMBER: 0, AIR_TANKER: 0, TRANSPORT_HELI: 0, DESTROYER: 0, LANDER: 0,
  },
  TANK: {
    INFANTRY: 75, RECON: 80, TANK: 55, HEAVY_TANK: 40, ANTI_TANK: 45, ARTILLERY: 70, ANTI_AIR: 65, FLAK_TANK: 75, MISSILE_AA: 80,
    SUPPLY_TRUCK: 100, TRANSPORT_TRUCK: 80, FIGHTER: 0, BOMBER: 0, ATTACKER: 0, STEALTH_BOMBER: 0, AIR_TANKER: 0, TRANSPORT_HELI: 0, DESTROYER: 0, LANDER: 0,
  },
  HEAVY_TANK: {
    INFANTRY: 90, RECON: 95, TANK: 75, HEAVY_TANK: 55, ANTI_TANK: 65, ARTILLERY: 85, ANTI_AIR: 75, FLAK_TANK: 85, MISSILE_AA: 90,
    SUPPLY_TRUCK: 120, TRANSPORT_TRUCK: 95, FIGHTER: 0, BOMBER: 0, ATTACKER: 0, STEALTH_BOMBER: 0, AIR_TANKER: 0, TRANSPORT_HELI: 0, DESTROYER: 0, LANDER: 0,
  },
  ANTI_TANK: {
    INFANTRY: 65, RECON: 75, TANK: 85, HEAVY_TANK: 70, ANTI_TANK: 50, ARTILLERY: 70, ANTI_AIR: 60, FLAK_TANK: 75, MISSILE_AA: 80,
    SUPPLY_TRUCK: 95, TRANSPORT_TRUCK: 75, FIGHTER: 0, BOMBER: 0, ATTACKER: 0, STEALTH_BOMBER: 0, AIR_TANKER: 0, TRANSPORT_HELI: 0, DESTROYER: 0, LANDER: 0,
  },
  ARTILLERY: {
    INFANTRY: 80, RECON: 75, TANK: 50, HEAVY_TANK: 40, ANTI_TANK: 50, ARTILLERY: 65, ANTI_AIR: 60, FLAK_TANK: 60, MISSILE_AA: 75,
    SUPPLY_TRUCK: 95, TRANSPORT_TRUCK: 75, FIGHTER: 0, BOMBER: 0, ATTACKER: 0, STEALTH_BOMBER: 0, AIR_TANKER: 0, TRANSPORT_HELI: 0, DESTROYER: 0, LANDER: 0,
  },
  ANTI_AIR: {
    INFANTRY: 95, RECON: 100, TANK: 25, HEAVY_TANK: 15, ANTI_TANK: 45, ARTILLERY: 75, ANTI_AIR: 55, FLAK_TANK: 50, MISSILE_AA: 60,
    SUPPLY_TRUCK: 120, TRANSPORT_TRUCK: 100, FIGHTER: 65, BOMBER: 65, ATTACKER: 80, STEALTH_BOMBER: 60, AIR_TANKER: 90, TRANSPORT_HELI: 100, DESTROYER: 0, LANDER: 0,
  },
  FLAK_TANK: {
    INFANTRY: 55, RECON: 45, TANK: 15, HEAVY_TANK: 10, ANTI_TANK: 20, ARTILLERY: 35, ANTI_AIR: 30, FLAK_TANK: 30, MISSILE_AA: 35,
    SUPPLY_TRUCK: 55, TRANSPORT_TRUCK: 45, FIGHTER: 80, BOMBER: 90, ATTACKER: 100, STEALTH_BOMBER: 85, AIR_TANKER: 105, TRANSPORT_HELI: 110, DESTROYER: 0, LANDER: 0,
  },
  MISSILE_AA: {
    INFANTRY: 0, RECON: 0, TANK: 0, HEAVY_TANK: 0, ANTI_TANK: 0, ARTILLERY: 0, ANTI_AIR: 0, FLAK_TANK: 0, MISSILE_AA: 0,
    SUPPLY_TRUCK: 0, TRANSPORT_TRUCK: 0, FIGHTER: 95, BOMBER: 105, ATTACKER: 115, STEALTH_BOMBER: 100, AIR_TANKER: 120, TRANSPORT_HELI: 125, DESTROYER: 0, LANDER: 0,
  },
  SUPPLY_TRUCK: {
    INFANTRY: 0, RECON: 0, TANK: 0, HEAVY_TANK: 0, ANTI_TANK: 0, ARTILLERY: 0, ANTI_AIR: 0, FLAK_TANK: 0, MISSILE_AA: 0,
    SUPPLY_TRUCK: 0, TRANSPORT_TRUCK: 0, FIGHTER: 0, BOMBER: 0, ATTACKER: 0, STEALTH_BOMBER: 0, AIR_TANKER: 0, TRANSPORT_HELI: 0, DESTROYER: 0, LANDER: 0,
  },
  TRANSPORT_TRUCK: {
    INFANTRY: 0, RECON: 0, TANK: 0, HEAVY_TANK: 0, ANTI_TANK: 0, ARTILLERY: 0, ANTI_AIR: 0, FLAK_TANK: 0, MISSILE_AA: 0,
    SUPPLY_TRUCK: 0, TRANSPORT_TRUCK: 0, FIGHTER: 0, BOMBER: 0, ATTACKER: 0, STEALTH_BOMBER: 0, AIR_TANKER: 0, TRANSPORT_HELI: 0, DESTROYER: 0, LANDER: 0,
  },
  FIGHTER: {
    INFANTRY: 0, RECON: 0, TANK: 0, HEAVY_TANK: 0, ANTI_TANK: 0, ARTILLERY: 0, ANTI_AIR: 0, FLAK_TANK: 0, MISSILE_AA: 0,
    SUPPLY_TRUCK: 0, TRANSPORT_TRUCK: 0, FIGHTER: 65, BOMBER: 85, ATTACKER: 105, STEALTH_BOMBER: 75, AIR_TANKER: 115, TRANSPORT_HELI: 120, DESTROYER: 0, LANDER: 0,
  },
  BOMBER: {
    INFANTRY: 110, RECON: 105, TANK: 80, HEAVY_TANK: 65, ANTI_TANK: 80, ARTILLERY: 80, ANTI_AIR: 30, FLAK_TANK: 35, MISSILE_AA: 40,
    SUPPLY_TRUCK: 120, TRANSPORT_TRUCK: 95, FIGHTER: 0, BOMBER: 0, ATTACKER: 0, STEALTH_BOMBER: 0, AIR_TANKER: 0, TRANSPORT_HELI: 0, DESTROYER: 0, LANDER: 0,
  },
  ATTACKER: {
    INFANTRY: 95, RECON: 95, TANK: 60, HEAVY_TANK: 45, ANTI_TANK: 60, ARTILLERY: 60, ANTI_AIR: 20, FLAK_TANK: 25, MISSILE_AA: 30,
    SUPPLY_TRUCK: 105, TRANSPORT_TRUCK: 80, FIGHTER: 0, BOMBER: 0, ATTACKER: 0, STEALTH_BOMBER: 0, AIR_TANKER: 0, TRANSPORT_HELI: 0, DESTROYER: 0, LANDER: 0,
  },
  STEALTH_BOMBER: {
    INFANTRY: 110, RECON: 90, TANK: 75, HEAVY_TANK: 60, ANTI_TANK: 70, ARTILLERY: 80, ANTI_AIR: 40, FLAK_TANK: 0, MISSILE_AA: 0,
    SUPPLY_TRUCK: 100, TRANSPORT_TRUCK: 80, FIGHTER: 30, BOMBER: 70, ATTACKER: 80, STEALTH_BOMBER: 55, AIR_TANKER: 90, TRANSPORT_HELI: 95, DESTROYER: 0, LANDER: 0,
  },
  AIR_TANKER: {
    INFANTRY: 0, RECON: 0, TANK: 0, HEAVY_TANK: 0, ANTI_TANK: 0, ARTILLERY: 0, ANTI_AIR: 0, FLAK_TANK: 0, MISSILE_AA: 0,
    SUPPLY_TRUCK: 0, TRANSPORT_TRUCK: 0, FIGHTER: 0, BOMBER: 0, ATTACKER: 0, STEALTH_BOMBER: 0, AIR_TANKER: 0, TRANSPORT_HELI: 0, DESTROYER: 0, LANDER: 0,
  },
  TRANSPORT_HELI: {
    INFANTRY: 0, RECON: 0, TANK: 0, HEAVY_TANK: 0, ANTI_TANK: 0, ARTILLERY: 0, ANTI_AIR: 0, FLAK_TANK: 0, MISSILE_AA: 0,
    SUPPLY_TRUCK: 0, TRANSPORT_TRUCK: 0, FIGHTER: 0, BOMBER: 0, ATTACKER: 0, STEALTH_BOMBER: 0, AIR_TANKER: 0, TRANSPORT_HELI: 0, DESTROYER: 0, LANDER: 0,
  },
  DESTROYER: {
    INFANTRY: 50, RECON: 0, TANK: 45, HEAVY_TANK: 35, ANTI_TANK: 0, ARTILLERY: 60, ANTI_AIR: 0, FLAK_TANK: 0, MISSILE_AA: 0,
    SUPPLY_TRUCK: 65, TRANSPORT_TRUCK: 50, FIGHTER: 0, BOMBER: 0, ATTACKER: 0, STEALTH_BOMBER: 0, AIR_TANKER: 0, TRANSPORT_HELI: 0, DESTROYER: 70, LANDER: 90,
  },
  LANDER: {
    INFANTRY: 0, RECON: 0, TANK: 0, HEAVY_TANK: 0, ANTI_TANK: 0, ARTILLERY: 0, ANTI_AIR: 0, FLAK_TANK: 0, MISSILE_AA: 0,
    SUPPLY_TRUCK: 0, TRANSPORT_TRUCK: 0, FIGHTER: 0, BOMBER: 0, ATTACKER: 0, STEALTH_BOMBER: 0, AIR_TANKER: 0, TRANSPORT_HELI: 0, DESTROYER: 0, LANDER: 0,
  },
};

export const getBaseDamage = (attackerType: UnitType, defenderType: UnitType): number =>
  BASE_DAMAGE_TABLE[attackerType][defenderType];
