import type { UnitDefinition, UnitType } from '@core/types/unit';

export const UNIT_DEFINITIONS: Record<UnitType, UnitDefinition> = {
  INFANTRY: {
    type: 'INFANTRY',
    cost: 1000,
    movementType: 'FOOT',
    moveRange: 3,
    maxFuel: 99,
    maxAmmo: 9,
    canCapture: true,
    attackRangeMin: 1,
    attackRangeMax: 1,
  },
  RECON: {
    type: 'RECON',
    cost: 4000,
    movementType: 'WHEEL',
    moveRange: 6,
    maxFuel: 80,
    maxAmmo: 9,
    canCapture: false,
    attackRangeMin: 1,
    attackRangeMax: 1,
  },
  TANK: {
    type: 'TANK',
    cost: 7000,
    movementType: 'TREAD',
    moveRange: 5,
    maxFuel: 70,
    maxAmmo: 6,
    canCapture: false,
    attackRangeMin: 1,
    attackRangeMax: 1,
  },
  ANTI_TANK: {
    type: 'ANTI_TANK',
    cost: 6000,
    movementType: 'TREAD',
    moveRange: 4,
    maxFuel: 70,
    maxAmmo: 6,
    canCapture: false,
    attackRangeMin: 1,
    attackRangeMax: 1,
  },
  ARTILLERY: {
    type: 'ARTILLERY',
    cost: 6000,
    movementType: 'TREAD',
    moveRange: 4,
    maxFuel: 50,
    maxAmmo: 6,
    canCapture: false,
    attackRangeMin: 2,
    attackRangeMax: 3,
  },
  ANTI_AIR: {
    type: 'ANTI_AIR',
    cost: 8000,
    movementType: 'TREAD',
    moveRange: 5,
    maxFuel: 60,
    maxAmmo: 6,
    canCapture: false,
    attackRangeMin: 1,
    attackRangeMax: 1,
  },
  FIGHTER: {
    type: 'FIGHTER',
    cost: 16000,
    movementType: 'AIR',
    moveRange: 8,
    maxFuel: 80,
    maxAmmo: 6,
    canCapture: false,
    attackRangeMin: 1,
    attackRangeMax: 1,
  },
  BOMBER: {
    type: 'BOMBER',
    cost: 18000,
    movementType: 'AIR',
    moveRange: 7,
    maxFuel: 70,
    maxAmmo: 6,
    canCapture: false,
    attackRangeMin: 1,
    attackRangeMax: 1,
  },
  DESTROYER: {
    type: 'DESTROYER',
    cost: 20000,
    movementType: 'NAVAL',
    moveRange: 6,
    maxFuel: 99,
    maxAmmo: 6,
    canCapture: false,
    attackRangeMin: 1,
    attackRangeMax: 2,
  },
  LANDER: {
    type: 'LANDER',
    cost: 12000,
    movementType: 'NAVAL',
    moveRange: 6,
    maxFuel: 99,
    maxAmmo: 0,
    canCapture: false,
    attackRangeMin: 1,
    attackRangeMax: 1,
  },
};
